# Generated by Django 3.0.4 on 2020-03-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='SOME STRING', max_length=200)),
                ('name', models.CharField(default='SOME STRING', max_length=100)),
                ('email', models.CharField(default='SOME STRING', max_length=100)),
                ('phoneNo', models.IntegerField(default=0)),
                ('password', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='SOME STRING', max_length=200)),
                ('name', models.CharField(default='SOME STRING', max_length=100)),
                ('email', models.CharField(default='SOME STRING', max_length=100)),
                ('phoneNo', models.IntegerField(default=0)),
                ('password', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('package_no', models.IntegerField(default=0)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Chef')),
                ('customer', models.ManyToManyField(to='food.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME STRING', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Chef')),
                ('packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Main_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME STRING', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Chef')),
                ('packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Appti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME STRING', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Chef')),
                ('packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Package')),
            ],
        ),
    ]
