# Generated by Django 3.0.2 on 2020-04-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200407_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Price_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.IntegerField(default=0)),
                ('food_name', models.CharField(default='SOME STRING', max_length=100)),
                ('chef', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('food_Type', models.CharField(default='SOME STRING', max_length=100)),
            ],
        ),
    ]
