# Generated by Django 3.0.4 on 2020-04-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_food_price_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_price_day',
            old_name='food_Type',
            new_name='foodName',
        ),
        migrations.RenameField(
            model_name='food_price_day',
            old_name='food_name',
            new_name='foodType',
        ),
    ]
