# Generated by Django 3.0.4 on 2020-04-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_album_musician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_set', to='food.Chef'),
        ),
    ]
