# Generated by Django 3.0.4 on 2020-04-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20200419_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='customer',
            field=models.ManyToManyField(blank=True, null=True, to='food.Customer'),
        ),
    ]
