# Generated by Django 3.0.4 on 2020-04-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_remove_package_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appti',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='main_menu',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sweet',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
