# Generated by Django 3.0.4 on 2020-04-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_remove_package_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='customer',
            field=models.ManyToManyField(blank=True, null=True, to='food.Customer'),
        ),
    ]
