# Generated by Django 3.0.4 on 2020-05-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_package_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appti',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='main_menu',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sweet',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
